name: CI/CD Tamarobot

on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Node.js pour le backend
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Installer les dépendances du backend
      - name: Install Backend Dependencies
        run: |
          cd ./backend
          npm install

      # Lancer les tests Jest pour le backend
      - name: Run Jest Tests (Backend)
        run: |
          cd ./backend
          npm test

  e2e-test:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Node.js pour le frontend
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Installer les dépendances du frontend
      - name: Install Frontend Dependencies
        run: |
          cd ./frontend
          npm install
