name: CI/CD Tamarobot

on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd ./backend
          npm install
          
      # Fixer les permissions pour Jest et les fichiers Node
      - name: Fix Permissions for Jest and Node.js
        run: |
          cd ./backend
          chmod -R 755 ./node_modules/.bin
          chmod -R 755 ./node_modules/jest

      - name: Run Jest Tests (Backend)
        run: |
          cd ./backend
          npm test
