name: Tama Jest Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js (version 18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          cd ./backend
          npm install

      # 4. Fix permissions for Jest and Node.js
      - name: Fix Permissions for Jest and Node.js
        run: |
          cd ./backend
          chmod -R 755 ./node_modules/.bin
          chmod -R 755 ./node_modules/jest

      # 5. Verify Node.js and npm versions
      - name: Verify Node.js and npm versions
        run: |
          node --version
          npm --version

      # 6. Run Jest Tests
      - name: Run Jest Tests
        run: |
          cd ./backend
          npm test

