name: ci-cd-tamarobot

# Déclenchement automatique du workflow
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Recupère le code source depuis Github
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (version 18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      #  Installe les dépendances backend
      - name: Install dependencies
        run: |
          cd ./backend
          npm install

      #  Run Jest Tests
      - name: Run Jest Tests
        run: |
          cd ./backend
          npm test
          
  sonarcloud:
    runs-on: ubuntu-latest
    needs: test

    steps:
      #Recupere le code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js # Node.js requis pour exécuter sonar-scanner via npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=Arheee_TamaRobotV2 \
            -Dsonar.organization=arheee \
            -Dsonar.sources=./backend \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN   
        # Analyse du code sonarCloud
        # - Vérifie bugs, code smells, duplication, couverture, sécurité
        # - Utilise les variables d’environnement pour ne pas exposer le token
        
  snyk-security:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

# Job pour construire l'image Docker du backend
  docker-build:
    runs-on: ubuntu-latest  # Utilisation de l'environnement Ubuntu
    needs: test  # Ce job dépend de la réussite du job "test"
    
    steps:
      # 1. Checkout le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t tamarobot-backend ./backend  