name: CI/CD Tamarobot

on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Node.js et les dépendances backend
      - name: Setup Node.js and Install Backend Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Backend Dependencies
        run: |
          cd ./backend
          npm install

      # Fixer les permissions pour Jest et les fichiers Node
      - name: Fix Permissions for Jest
        run: |
          cd ./backend
          sudo chmod -R 755 ./node_modules/.bin
          sudo chmod -R 755 ./node_modules/jest

      # Lancer les tests Jest (backend)
      - name: Run Jest Tests (Backend)
        run: |
          cd ./backend
          npm test

  e2e-test:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Node.js et les dépendances frontend
      - name: Setup Node.js and Install Frontend Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Frontend Dependencies
        run: |
          cd ./frontend
          npm install

      # Lancer les tests Cypress (frontend)
      - name: Run Cypress Tests (Frontend)
        run: |
          cd ./frontend
          npx cypress run --headless
